### ISSUE TITLE
.simplify works incorrect

### ISSUE THREAD

**Issue by TrejGun** [LarryBattle/Ratio.js#57]
``` js
var x = Ratio.parse("6234/6460");
console.log(x.toString()); // 6234/6460
console.log(x.simplify().toString()); // 4776826625387/4950000000000
```

**Comment by CTAPbIuMABP** [comment]
almost one year have passed and this critical bug is not yet fixed. shame on you.

**Comment by LarryBattle** [comment]
Sorry about that, I just haven't had the motivation to work on this project anymore.
I tried your change but it broke a few other test cases. I think I found a solution but lost focus to complete the fix.
I'll keep this issue open until a proper fix comes about.

**Comment by LarryBattle** [comment]
Please checkout these projects.
- https://github.com/MikeMcl/decimal.js
- https://github.com/dtrebbien/BigDecimal.js
