### ISSUE TITLE
Why is the project retired?

### ISSUE THREAD

**Issue by josdejong** [LarryBattle/Ratio.js#78]
Since 3 march the readme states that Ratio.js is retired, and links to two BigNumber libraries (which aren't alternatives at all, they can't represent most fractions like `1/3`, `2/7`, etc). Why is the project retired?

**Comment by LarryBattle** [comment]
Support. https://github.com/LarryBattle/Ratio.js/issues/57#issuecomment-76654615

**Comment by josdejong** [comment]
Thanks for the clarification. 

You could put a message "looking for someone to take over the project" instead ;)

**Comment by LarryBattle** [comment]
done
