### ISSUE TITLE
Project transfer

### ISSUE THREAD

**Issue by infusion** [LarryBattle/Ratio.js#79]
Hi,

as ratio.js doesn't get support anymore, I would like to take over and merge it with my very own fraction.js. If you don't want to work anymore on the project, you can transfer it to my account like described here: https://help.github.com/articles/transferring-a-repository/

Robert

**Comment by LarryBattle** [comment]
I need to look into your project and see if it's a good fit.
http://www.xarg.org/2014/03/precise-calculations-in-javascript/

**Comment by infusion** [comment]
Okay :) What do you say? 
BTW: I just published a huge update of my lib.

**Comment by LarryBattle** [comment]
The name Fraction.js is already taken by https://github.com/ekg/fraction.js 

Sorry but I feel more comfortable just pointing to your repo from the readme instead of transferring ownership.
If you want I could make you a collaborators ...

**Comment by infusion** [comment]
If you feel more comfortable to just mention my lib as an alternative, it's also fine. BTW: Both examples you currently mentioning are no alternatives to ratio.js:

https://github.com/MikeMcl/decimal.js
https://github.com/dtrebbien/BigDecimal.js

I don't know if it changes something, but I can tell you, what I was planning to do with the transferred ownership: I wanted to maintain your API through the added dependency of my lib. The readme would have a note that you were the owner and held the copyright until $today and of course that the project has been moved. A new version tag would be added, so that people could checkout your code as well.

After that, I'd work through your open tickets and fix them, either as an extension to my lib, which gets passed through to your or maybe they are already handled and no further work would be needed.

About the name. I know there is another project called fraction.js. But not having a distinct name doesn't harm anyone, I think. It's not a brand name like "jquery". It's a describing name and so it's a fraction lib by ekg and a fraction lib written by me.

Robert

**Comment by LarryBattle** [comment]
ok. I'll still keep that in mind.
In the meantime, I added your library as an alternative on the readme.

**Comment by infusion** [comment]
Thanks, but you haven't added mine ;)

**Comment by LarryBattle** [comment]
LOL. Corrected.
